server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: OrderService
          uri: lb://event-order-service
          predicates:
            - Path=/order/**

        - id: NoificationService
          uri: lb://event-product-service
          predicates:
            - Path=/product/**