server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: OrderService
          uri: lb://event-order-service
          predicates:
            - Path=/order/**

        - id: NotificationService
          uri: lb://event-product-service
          predicates:
            - Path=/product/**